### ISSUE TITLE
Lifetime Fitting

### ISSUE THREAD

**Issue by ncodina** [tritemio/FRETBursts#48]
I was wondering if there is already some function implemented to calculate lifetimes from the TCSPC histogram?

**Comment by tritemio** [comment]
Not out-of-the-box, but you can use straight lmfit to do the fitting. You find an example of fitting with deconvolution using least-squares or maximum likelihood in this notebook (uses simulated data):

https://github.com/tritemio/notebooks/blob/master/Lifetime_decay_fit.ipynb

Also you can fairly simply compute a per-burst "mean lifetime" with:

http://fretbursts.readthedocs.io/en/latest/plugins.html#fretbursts.burstlib_ext.calc_mean_lifetime

This can be used, for example, to build the plots like *mean lifetime* vs *ratiometric E* (see Seidel group MFD analysis).

**Comment by tritemio** [comment]
The notebooks recently published in [this repository](https://github.com/tritemio/polimi_tcspc_16ch/blob/master/16-CH%20POLIMI-TCSPC%20Bursts%20Analysis-2015-09-08_s5_FRET.ipynb) show how to do lifetime fitting on multispot data using both tail fitting and IRF reconvolution of the lifetime histogram with different models (1, 2 or 3 exponentials).

The notebooks are pretty long, for the part relative to lifetime fitting see this section:

http://nbviewer.jupyter.org/github/tritemio/polimi_tcspc_16ch/blob/master/16-CH%20POLIMI-TCSPC%20Bursts%20Analysis-2015-09-08_s5_FRET.ipynb#Population-Lifetime-Fit

**Comment by tritemio** [comment]
This issue was moved to OpenSMFS/FRETBursts#6
