### ISSUE TITLE
burst_search and burst_search_and_gate

### ISSUE THREAD

**Issue by ncodina** [tritemio/FRETBursts#49]
Hi,
I would like to understand what the searches: `burst_search` and `burst_search_and_gate` do.

In the following `burst_search` command:
```python
d.burst_search(F = 6, m = 10, ph_sel = Ph_sel('all'))
```
We are looking for bursts where 10 (m) consecutive photons are in a time window ≤T (calculated from 6 (F) times the background rate). Do this 10 photons take into account Donor and Acceptor, (so we are not identifying the burst separately for donor and acceptor, but looking at them together)?
Does the `burst_search` function go through `d.ph_times_m`, and looks at 10 consecutive timestamps (donor and acceptor)? 

This is the result we obtain after using this search:

<img width="622" alt="screen shot 2016-11-25 at 16 01 39" src="https://cloud.githubusercontent.com/assets/23275480/20630698/779bac0c-b32a-11e6-9e66-75b3eaf67c7a.png">

We get a different result when using `burst_search_and_gate`:
```python
d_dcbs = bext.burst_search_and_gate(d, F=6,m=10, ph_sel1=Ph_sel(Dex='Dem'), ph_sel2=Ph_sel(Dex='Aem'))
```

<img width="620" alt="screen shot 2016-11-25 at 16 03 09" src="https://cloud.githubusercontent.com/assets/23275480/20630712/8a9a763a-b32a-11e6-966e-4a9df03cc1e8.png">

In this case are we identifying the bursts first separately for donor and acceptor, and then only taking into account the bursts present in both, and their duration is the intersection of the two overlapping bursts?

In our case, smFRET, should we use `burst_search`?
Is  `burst_search_and_gate` used for PIE measurements but comparing the bursts after donor excitation to bursts after acceptor excitation?

**Comment by tritemio** [comment]
`Data.burst_search` performs a burst search on the photon stream that you specify, which by default is all-photons. You can also specify Dem or Aem photon streams. For example I use D-em burst search to accurately fit the D-only peak and estimate the leakage.

`bext.burst_search_and_gate` performs two burst searches on two photon streams and then takes the intersection (the overlapping portion) of the two sets of bursts.

That said, you usually use `bext.burst_search_and_gate` on ALEX or PIE measurements where the two streams are Dex and Aex. In this way you automatically filter out D-only and A-only molecules. With this selection of photon streams this is the so called Dual-Channel Burst Search (DCBS) proposed by Eyal Nir.

In single-excitation measurement you can use the simpler `Data.burst_search`. 
Remember also to filter the burst by size after burst search (with a threshold of at least 20-30 photons) to get histograms with less shot-noise.

**Comment by tritemio** [comment]
@ncodina, does this question needs more clarification? Do we need to improve the documentation in regard?

**Comment by ncodina** [comment]
No, thanks very much for the information. 

I was confused initially because I thought that the information for donor and acceptor channels may be stored separately. I believed that bursts in the donor and acceptor channel might be identified separately first, and then compared.

But I can see that `d.ph_times_m` contains all the timestamps (donor + acceptor) in one channel. And the bursts are identified from this list, by looking at all photons, donor and acceptor.

**Comment by tritemio** [comment]
Ok, thanks. closing then.
