### ISSUE TITLE
Burst data

### ISSUE THREAD

**Issue by kfriedl** [tritemio/FRETBursts#63]
I'd like to extract the burst data after a burstsearch and store it in a file. As far as I can see, the burst start and stop information is stored in the burstlib.data object. How can I add the detection channel and excitation period information?

**Comment by tritemio** [comment]
I recommend exporting all the burst data in a DataFrame with the function:

[`bext.burst_data`](http://fretbursts.readthedocs.io/en/latest/plugins.html?highlight=burst_data#fretbursts.burstlib_ext.burst_data)

For your info, the core burst data is  in `Data.mbursts` (a list of `Bursts` objects). `Bursts` object contain minimal information such as burst start/stop and a [few other properties](http://fretbursts.readthedocs.io/en/latest/burstsearch.html?highlight=Bursts#fretbursts.phtools.burstsearch.Bursts). Keep in mind that `Bursts` gives counts with no correction, and burst durations  and times in timestamps_units.

Conversely `bext.burst_data` returns corrected counts in all the different stream, times in milliseconds and basically all the burst information contained in additional `Data` attributes.

**Comment by tritemio** [comment]
Also, one of FRETBursts notebooks shows how to export burst data and timestamps in each burst:

- [Example - Exporting Burst Data Including Timestamps](http://nbviewer.jupyter.org/github/tritemio/FRETBursts_notebooks/blob/master/notebooks/Example%20-%20Exporting%20Burst%20Data%20Including%20Timestamps.ipynb)

**Comment by tritemio** [comment]
This issue was moved to OpenSMFS/FRETBursts#1
