### ISSUE TITLE
Export "Inter-photon delay times" graph to .csv file

### ISSUE THREAD

**Issue by ncodina** [tritemio/FRETBursts#68]
Hi,
I want to export the data of the "Inter-photon delay times" to a .csv file. How would I do it?

![figure_1](https://user-images.githubusercontent.com/23275480/43395167-0ab3836e-93f5-11e8-87a8-bfd8292a3a2f.png)

**Comment by tritemio** [comment]
Hi @ncodina, 

I moved your issue to https://github.com/OpenSMFS/FRETBursts/issues/17

See my reply there. Please use the OpenSMFS address in the future.
