### ISSUE TITLE
Reading Photon-HDF5 files of 'generic' type into FRETbursts

### ISSUE THREAD

**Issue by AndersBarth** [tritemio/FRETBursts#69]
Hi,

I have data from a PIE-MFD setup (i.e. nsALEX with polarization) that I am trying to read from a Photon-HDF5 file into FRETbursts (file is attached). The file specifies the number of polarizations (/setup/num_polarization_ch = 2) and the polarization assignment (/photon_data/measurement_specs/detectors_specs/polarization_ch1-2), yet I get the following error upon trying to read the file:

`Invalid_PhotonHDF5: The field `/setup/num_polarization_ch` indicates more than one polarization.
However, some `detectors_specs/polarization_ch*` fields are missing.`

The file was generated through phforge 0.1.1 using phconvert 0.8.2.

Since all the required fields are present when inspecting the file in HDFView, I'm confused why the error occurs.
Thanks for the help!

Best,
Anders

[Link to File H20.h5](https://drive.google.com/open?id=1AS6_Y2FDeYsBfxSywR9gYbEgNkH5mtUR)

**Comment by AndersBarth** [comment]
Small update:

I looked into the code and it seems that the logic check in loader.py on line 134:

`if any('polarization_ch%i' not in det_specs for i in (1, 2)):`

returns True when it shouldn't.

It works if changed to:

`if not (('polarization_ch1'  in det_specs) and ('polarization_ch2'  in det_specs)):`

but there is probably a more pythonic way of solving it.

**Comment by tritemio** [comment]
Thanks for the report. I migrated the issue to https://github.com/OpenSMFS/FRETBursts/issues/18.  See my reply there.

In the future, please open issues in the new FRETBursts repository under the OpenSMFS organization, thanks.
