### ISSUE TITLE
ymin and ymax deprication warning for Matplotlib 3.2

### ISSUE THREAD

**Issue by mayeshh** [tritemio/FRETBursts#71]
I am getting a persistent deprecation warning for many of the `dplot()` functions.

This is the error:

`/Users/maya/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_base.py:3610: MatplotlibDeprecationWarning: 
The `ymax` argument was deprecated in Matplotlib 3.0 and will be removed in 3.2. Use `top` instead.
  alternative='`top`', obj_type='argument')
/Users/maya/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_base.py:3604: MatplotlibDeprecationWarning: 
The `ymin` argument was deprecated in Matplotlib 3.0 and will be removed in 3.2. Use `bottom` instead.
  alternative='`bottom`', obj_type='argument')`

Repeated many times.

I have gone into my copy of burst_plot.py and changed all instances of `ymax` to `top` and `ymin` to `bottom`. I saved the file and relaunched the notebook, but the warning persists.

**Comment by tritemio** [comment]
@mayeshh, can you please open this issue on the [FRETBursts repo in the OpenSMFS organization](https://github.com/OpenSMFS/FRETBursts)? The repo here is not the official one anymore, thanks.
